### ISSUE TITLE
Accuracy as an Attribute?

### ISSUE THREAD

**Issue by Insighttful** [davidberenstein1957/spacy-setfit#7]
Provided a eval_dataset, I see the accuracy printed but how can it be accessed programmatically?

```Python
    nlp.add_pipe(
        "text_categorizer",
        config={
            "pretrained_model_name_or_path": "paraphrase-MiniLM-L3-v2",
            "setfit_trainer_args": {
                "train_dataset": train_dataset,
                "eval_dataset": eval_dataset,
                "num_iterations": 5,
                "column_mapping": {"text": "text", "label": "label"},
            },
        },
    )
```

Also based on the docs example:
```Python
setfit_trainer_args = {
    "train_dataset": train_data,
    "eval_dataset": eval_data,
    "num_iterations": 20,
    "num_epochs": 1,
    "learning_rate": 2e-5,
    "batch_size": 16,
    "seed": 42,
    "column_mapping": column_map,
    "use_amp": False
}
```
If an int is provided for `batch_size`, an error is raised that a float is not accepted.

**Comment by Insighttful** [comment]
When `batch_size = 16` set manually in `setfit_trainer_args` instead of using defaults.

```Bash
Traceback (most recent call last):
  File "/Users/anon/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8214.51/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/anon/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8214.51/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/anon/Developer/***************/modules/classifiers/training/train_*********.py", line 200, in <module>
    train()
  File "/Users/anon/Developer/***************/modules/classifiers/training/train_*********.py", line 192, in train
    nlp, model_name = train_on_annotations(df)
  File "/Users/anon/Developer/***************/modules/classifiers/training/train_*********.py", line 163, in train_on_annotations
    nlp.add_pipe(
  File "/Users/anon/Developer/***************/.venv/lib/python3.10/site-packages/spacy/language.py", line 814, in add_pipe
    pipe_component = self.create_pipe(
  File "/Users/anon/Developer/***************/.venv/lib/python3.10/site-packages/spacy/language.py", line 702, in create_pipe
    resolved = registry.resolve(cfg, validate=validate)
  File "/Users/anon/Developer/***************/.venv/lib/python3.10/site-packages/confection/__init__.py", line 733, in resolve
    resolved, _ = cls._make(
  File "/Users/anon/Developer/***************/.venv/lib/python3.10/site-packages/confection/__init__.py", line 782, in _make
    filled, _, resolved = cls._fill(
  File "/Users/anon/Developer/***************/.venv/lib/python3.10/site-packages/confection/__init__.py", line 854, in _fill
    getter_result = getter(*args, **kwargs)
  File "/Users/anon/Developer/***************/.venv/lib/python3.10/site-packages/spacy_setfit/__init__.py", line 42, in create_setfit_model
    return SpacySetFit.from_trained(
  File "/Users/anon/Developer/***************/.venv/lib/python3.10/site-packages/spacy_setfit/models.py", line 73, in from_trained
    trainer.train()
  File "/Users/anon/Developer/***************/.venv/lib/python3.10/site-packages/setfit/trainer.py", line 384, in train
    train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=batch_size)
  File "/Users/anon/Developer/***************/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 357, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "/Users/anon/Developer/***************/.venv/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 232, in __init__
    raise ValueError("batch_size should be a positive integer value, "
ValueError: batch_size should be a positive integer value, but got batch_size=16.0```

**Comment by davidberenstein1957** [comment]
Hi @Insighttful, I was on holidays so I missed this, but I will make sure to fix this in a patch.

**Comment by joel-odlund** [comment]
in the mean time,  this can be worked around by disabling the Spacy config validation 

```
    nlp.add_pipe(
        "text_categorizer",
         validate = False,
        config={
            "pretrained_model_name_or_path": "paraphrase-MiniLM-L3-v2",
            "setfit_trainer_args": {
                "train_dataset": train_dataset,
                "eval_dataset": eval_dataset,
                "num_iterations": 5,
                "column_mapping": {"text": "text", "label": "label"},
            },
        },
    )
```

**Comment by davidberenstein1957** [comment]
It has taken a while but I managed to resolve this :) Thanks for the feedback.
